// Generated by CoffeeScript 1.6.3
(function() {
  var buf, emblem, fs, handlebars, html, output, processStatements, result, _;

  fs = require("fs");

  emblem = require("emblem");

  handlebars = require("handlebars");

  html = require('html');

  _ = require("underscore");

  emblem.handlebarsVariant = handlebars;

  buf = fs.readFileSync("lib/slider.emblem", "utf8");

  result = emblem.parse(buf);

  processStatements = function(statements) {
    return _(statements).map(function(s) {
      var r;
      switch (s.type) {
        case 'content':
          return s.string;
        case 'block':
          debugger;
          r = [
            "{{" + s.mustache.id.original + " " + (_(s.mustache.params).map(function(p) {
              return p.string;
            }).join(' ')) + "}}"
          ];
          if (s.program != null) {
            r.push(processStatements(s.program.statements));
          }
          return r;
        default:
          return '';
      }
    });
  };

  output = _(processStatements(result.statements)).flatten().join('');

  fs.writeFileSync("output.hbs", html.prettyPrint(output));

}).call(this);
